---
galaxy_info:
  author: "Nicolas Landais"
  license: BSD
  min_Ansible_version: 1.4
  platforms:
   - name: EL
     versions:
      - 5
      - 6
   - name: Fedora
     versions:
      - 16
      - 17
      - 18
   - name: Ubuntu
     versions:
      - precise
      - quantal
      - raring
      - saucy
   - name: Debian
     versions:
      - wheezy
   - name: Windows
     versions:
      - 2012 R2
  categories:
   - system
dependencies: []
