---
- name: Create apppool
  win_iis_webapppool:
    name: "{{ item }}"
    state: started
    attributes: "managedRuntimeVersion:{{ version }}|managedPipelineMode:{{ pipelineMode }}|queueLength:1000|enable32BitAppOnWin64:true"
  with_items:
    - "{{ poolName }}"
    - "{{ webapp_poolName|default([]) }}"

- name: Start with a clean slate by deleting the site physical path
  win_file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ path }}"
    - "{{ webapp_path|default([]) }}"

- name: Create site physical path
  win_file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ path }}"

- name: Create directories under the site's root directory
  win_file:
    path: "{{ path }}\\{{ item }}"
    state: directory
  with_items:
    - logs

- name: Create web site
  win_iis_website:
    name: "{{ siteName }}"
    state: started
    ip: '*'
    application_pool: "{{ poolName }}"
    physical_path: "{{ path }}"
    port: 80

- name: start site
  win_iis_website:
    name: "{{ siteName }}"
    state: started

- name: Fetch the package from S3
  win_s3:
    bucket: "{{ s3_bucket }}"
    key: "{{ package }}"
    method: download
    overwrite: true
    local: '{{ download_dir }}'

- name: Unzip the release package
  win_unzip:
    src: '{{ download_dir }}\{{ package }}'
    dest: '{{ path }}'
    rm: true
