---
- name: Debug Create app pool
  debug:
    msg: "Create app pool {{ webapp_poolName }} with user sharefile"

- name: Create apppool
  win_iis_webapppool:
    name: "{{ item }}"
    state: started
    attributes: "managedRuntimeVersion:{{ version }}|managedPipelineMode:{{ pipelineMode }}|queueLength:1000|processModel.identityType:SpecificUser|processModel.userName:sharefile|processModel.password:{{ sharefile_user }}|enable32BitAppOnWin64:true"
  with_items:
    - "{{ webapp_poolName }}"

- name: Debug Create web application
  debug:
    msg: "Create application '{{ webapp_name }}' on site '{{ site }}' with path '{{ webapp_path }}' and pool '{{ webapp_poolName }}'"

- name: Create web application
  win_iis_webapplication:
    name: "{{ webapp_name }}"
    site: "{{ siteName }}"
    physical_path: "{{ webapp_path }}"
    application_pool: "{{ webapp_poolName }}"
