---
# tasks file for IIS
- name: Install IIS
  win_feature:
    name: "Web-Server"
    state: present
    include_sub_features: yes
    include_management_tools: yes
    restart: no

- name: Install modules
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - webpicmd
  ignore_errors: true

- name: Download Application Request Routing and Advanced logging packages
  win_webpicmd:
    name: "{{ item }}"
  with_items:
    - ARR
    - AdvancedLogging

- name: Set custom errors
  script: WebConfiguration.ps1

- name: Remove Default site folder
  win_file: path="c:\inetpub\wwwroot\Default site" state=absent

- name: Remove default web site
  win_iis_website:
    name: "Default Web Site"
    state: absent

- name: Restart the World Wide Web Publishing Service
  win_service:
    name: w3svc
    state: restarted
