---
- hosts: localhost
  gather_facts: no
  vars:
    inventory_tag: '{{ tag | regex_replace("\.", "_") }}'
  vars_files:
    - './roles/common/vars/defaults.yml'
  roles:
    - ec2-provision

- hosts: windows
  gather_facts: yes
  vars_files:
    - './roles/common/vars/defaults.yml'
  roles:
    - role: basic_config
    - { role: create_site }

# See http://54.165.232.145/view/Deployment%20jobs/job/provision_instance/ to see how this playbook is called and used in the AWS environment
# From the command prompt on the Ansible run:
# Ansible-playbook webserver.yml -e 'tag=samplewebapp region=us-east-1'
