---
# defaults file for create_site
siteName: apinew
version: v4.0
pipelineMode: Integrated
poolName: apinew
path: "c:\\inetpub\\wwwroot\\apinew"
http_binding_port: 801
https_binding_port: 4431
loopback_binding: true
cookie_timeout: 975